### ISSUE TITLE
add objects library

### ISSUE THREAD

**Issue by Sauron754** [Sauron754/SpaceScript#2]
Nomen est omen!

we probably need objects like:

- celestial bodies
- spaceship parts

**Comment by Sauron754** [comment]
which internal methods do the orbitalObjects and CMO classes need?

**Comment by taragor** [comment]
GetActualPosition
GetSOI

Sauron754 <notifications@github.com> schrieb am Mi., 19. Apr. 2017, 11:10:

**Comment by Sauron754** [comment]
What is GetSOI??

**Comment by taragor** [comment]
Sphere of influence

Sauron754 <notifications@github.com> schrieb am Mi., 19. Apr. 2017, 11:20:

**Comment by Sauron754** [comment]
Ah okay, i will now start working on the internal methods

**Comment by taragor** [comment]
Data handler nearly finished

Sauron754 <notifications@github.com> schrieb am Mi., 19. Apr. 2017, 13:50:

**Comment by taragor** [comment]
celestrial bodies need a vector to save their momentary veloity (needs to be getVelocity() of object)
(so do flights)
where to get the central body of the sattelite?

**Comment by Sauron754** [comment]
you mean parent body?? I would add a parent child dictionary and then after calling the class putting the name of the parents into the class.parent_str variable

then i found a way to call classes/variables from a string with the eval() function

**Comment by Sauron754** [comment]
will be on it with the velocity vector

**Comment by taragor** [comment]
parent child dictionary might work aswell. just might need to be quite regularily updated
EDIT: nah nvm
EDIT2: just needs to be checked if update necessary with every tick

**Comment by Sauron754** [comment]
just decided to change the getPosition function to setPosition, which will then set the variable position to a certain state -> now if you want to get the Position of the object just call object.position

**Comment by taragor** [comment]
working with public variables :O

**Comment by Sauron754** [comment]
pretty sure that every variable in python is public

**Comment by Sauron754** [comment]
one question how do you calculate the current position based on orbital elements? how do we eaven define our orbit??

**Comment by taragor** [comment]
i basicaly use the actual velocity and mass and distance to parent to calculate the gravitational force.
using the gravitational force i can calculate the acceleration and by using the time interval the new position and new velocity

**Comment by taragor** [comment]
it is not the most exact but the simplest way

**Comment by Sauron754** [comment]
but then we arent using predifined movement orbits but simulated environments

**Comment by Sauron754** [comment]
but do you think it will heavily influnece our performance if we calculate the celestial orbital movement?

**Comment by taragor** [comment]
i think using a simple simulation is more performance friendly than going for an predefined orbit
using my code we dont need to calculate if any point is an element of an orbital plane. neiter is there any need to calculate the length of a segment of a circle

**Comment by Sauron754** [comment]
okay well then eaven better; the only thing we will also need to calculate the Influence of the other body to the first; (what I mean by that is if we calculate the influence of obj 1 on obj 2, and if both objects are in comparable mass regions we also need to calculate obj 2 on obj 1)

**Comment by taragor** [comment]
we shouln't have any bodys of this criterea in our solar system
i guess...

**Comment by Sauron754** [comment]
so you mean that the planets wont interfere with each other and that the masses of their natural satelites are small enought that we can neglect them

**Comment by Sauron754** [comment]
do we still need a object.setPosition method if you have already implemented that in the mathCore??

**Comment by taragor** [comment]
mathcores calcOrbitalPosition(orbital_obj, time_float) returns the new orbital position of the body and updates its velocity

i think the body/sattelite constelation with the most simmilar masses is earth and lunar (lunar has barely 1/100 of earths mass so we shouldn't run into trouble there)

**Comment by Sauron754** [comment]
okay well then we dont need the object.setPosition method; we can just redefine the position in the main calcultaion process, which should actually be performance friendlier

okay well with 1/100 of the mass and the distance between these objects i think we can safely neglect them

**Comment by Sauron754** [comment]
doesnt luna have 1/6 of earths mass?

**Comment by taragor** [comment]
it has 1/6 of gravity but earth math is 5.something *10^24 whilst luna mass is 6.something * 10^22
EDIT: EARTH: 5,9 * 10^24 Moon 7,3 * 10^22

**Comment by Sauron754** [comment]
okay yes I see

**Comment by Sauron754** [comment]
do we actually need anything more for the objects.py file or can I close this issue??

**Comment by taragor** [comment]
found formula to calculate SOI more accurately https://en.wikipedia.org/wiki/Sphere_of_influence_(astrodynamics)

**Comment by Sauron754** [comment]
Oh nice I'll adapt it right away

**Comment by Sauron754** [comment]
okay done do we need anything else?
